// Pure TS — zero Phaser. Player attack simulation core.
// Ported from GameScene.doAttack + Enemy.takeDamage logic.

import { COMBAT, KNOCKDOWN_THRESHOLDS } from '../config/combat'
import { ENEMY_SCORE_TABLE, PLAYER_STATS } from '../config/stats'
import type { GameState, EnemyState, SimEvent } from '../types'

// ── Internal helpers ──────────────────────────────────────────────────────────

/** Compute the X origin of the hit box for a given attack kind. */
function hitOriginX(state: GameState, kind: 'punch' | 'kick'): number {
  const { charKey, x, facing, scaleX } = state.player
  const stats = PLAYER_STATS[charKey] ?? PLAYER_STATS['werdum']
  const reach = kind === 'punch' ? stats.punchReach : stats.kickReach
  return x + facing * reach * scaleX
}

/** Compute knockdown threshold for an enemy. Mirrors Enemy.takeDamage logic. */
function knockdownThreshold(e: EnemyState): number {
  if (e.enemyType === 'fat') return KNOCKDOWN_THRESHOLDS.fat
  if (e.enemyType === 'strong' || e.isBoss) return KNOCKDOWN_THRESHOLDS.boss
  return KNOCKDOWN_THRESHOLDS.default
}

/** Knockdown timer per enemy. Mirrors Enemy.enterKnockdown logic. */
function knockdownTimer(e: EnemyState): number {
  return e.isBoss ? 800 : 1500
}

/**
 * Apply `amount` damage to an enemy and return the updated enemy state plus
 * any events generated by the hit (enemyDied, enemyKnockdown, bossPhase2).
 *
 * Exported so the ally attack system can reuse it.
 */
export function applyDamageToEnemy(
  e: EnemyState,
  amount: number,
): { enemy: EnemyState; events: SimEvent[] } {
  const events: SimEvent[] = []

  const newHp = Math.max(0, e.hp - amount)

  // Base updated state (target + noHitTimer always change on any hit)
  let updated: EnemyState = {
    ...e,
    hp: newHp,
    target: 'player',
    noHitTimer: 0,
  }

  // Boss coco phase 2: hp drops below 100 for the first time
  if (updated.enemyType === 'boss_coco' && !updated.inPhase2 && updated.hp < 100) {
    updated = {
      ...updated,
      inPhase2: true,
      currentSpeed: updated.baseSpeed * 1.4,
    }
    events.push({ type: 'bossPhase2', id: updated.id })
  }

  // Death
  if (updated.hp <= 0) {
    updated = { ...updated, hp: 0, isDead: true, fsm: 'dead' }
    events.push({
      type: 'enemyDied',
      id: updated.id,
      enemyType: updated.enemyType,
      x: updated.x,
      y: updated.y,
    })
    return { enemy: updated, events }
  }

  // Knockdown check (only if not dead)
  if (amount >= knockdownThreshold(e)) {
    updated = { ...updated, fsm: 'knockdown', knockdownTimer: knockdownTimer(e) }
    events.push({ type: 'enemyKnockdown', id: updated.id })
  }

  return { enemy: updated, events }
}

// ── Public API ────────────────────────────────────────────────────────────────

export interface AttackResult {
  state: GameState
  events: SimEvent[]
}

/**
 * Pure player attack function.
 *
 * Returns a new GameState (input is never mutated) and the list of SimEvents
 * produced by the attack.
 *
 * Mirrors the logic in GameScene.doAttack line-by-line.
 */
export function performAttack(
  state: GameState,
  kind: 'punch' | 'kick',
): AttackResult {
  // Gate: cooldown or non-normal player state → no-op
  if (state.player.attackCooldown > 0 || state.player.fsm !== 'normal') {
    return { state, events: [] }
  }

  const spec = kind === 'punch' ? COMBAT.punch : COMBAT.kick
  const { damage, rangeH } = spec
  const rangeV = spec.rangeV

  const originX = hitOriginX(state, kind)
  const groundY = state.player.groundY

  const events: SimEvent[] = []
  let hitAny = false
  let newEnemies = state.enemies
  let newScore = state.score

  for (let i = 0; i < state.enemies.length; i++) {
    const e = state.enemies[i]
    // V1 behavior: skip ONLY dead enemies. Knocked-down enemies in range ARE
    // counted as hits (combo increment + hit event/feedback) but take NO damage.
    if (e.isDead) continue

    const dx = Math.abs(e.x - originX)
    const dy = Math.abs(e.y - groundY)

    if (dx < rangeH && dy < rangeV) {
      // Combo multiplier uses comboCount BEFORE increment (matches GameScene code)
      const comboMult =
        newScore.comboCount >= COMBAT.combo.tier2.hits ? COMBAT.combo.tier2.mult
        : newScore.comboCount >= COMBAT.combo.tier1.hits ? COMBAT.combo.tier1.mult
        : 1
      const finalDmg = Math.round(damage * comboMult)

      events.push({ type: 'hit', targetId: e.id, amount: finalDmg, x: e.x, y: e.y, source: 'player' })

      // V1: knocked-down enemies receive the hit event (feedback) but no damage.
      // Enemy.takeDamage already early-returns for knockdown in V1; the bridge
      // calls takeDamage per 'hit' event and relies on that guard.
      if (e.fsm !== 'knockdown') {
        const { enemy: updatedEnemy, events: enemyEvents } = applyDamageToEnemy(e, finalDmg)

        // Build updated enemies array (immutably)
        if (newEnemies === state.enemies) {
          newEnemies = state.enemies.slice()
        }
        newEnemies[i] = updatedEnemy
        events.push(...enemyEvents)

        // Score on kill: in GameScene addScore is called INSIDE the hit loop,
        // before comboCount++ (which happens after the loop). So we use the
        // PRE-increment comboCount for the score multiplier.
        const justDied = !e.isDead && updatedEnemy.isDead
        if (justDied) {
          // scoreMult uses pre-increment comboCount (matches GameScene.addScore)
          const scoreMult = Math.max(1, Math.floor(newScore.comboCount / 2))
          const scorePoints = ENEMY_SCORE_TABLE[updatedEnemy.enemyType] * scoreMult
          newScore = {
            ...newScore,
            score: newScore.score + scorePoints,
            enemiesDefeated: newScore.enemiesDefeated + 1,
          }
        }
      }

      hitAny = true
    }
  }

  // Update combo and comboTimer (score + enemiesDefeated already updated per-kill above)
  let finalScore = newScore
  if (hitAny) {
    const newComboCount = newScore.comboCount + 1
    const newComboTimer = COMBAT.combo.windowMs

    const milestones: SimEvent[] = []
    if (newComboCount === 10 || newComboCount === 20) {
      milestones.push({ type: 'comboMilestone', count: newComboCount })
    }

    finalScore = {
      ...newScore,
      comboCount: newComboCount,
      comboTimer: newComboTimer,
      maxComboReached: Math.max(newScore.maxComboReached, newComboCount),
    }

    events.push(...milestones)
  }

  // attackSwung event (always emitted, with hit flag)
  const swungEvent: SimEvent = { type: 'attackSwung', kind, hit: hitAny }
  // Insert attackSwung at front for clarity
  events.unshift(swungEvent)

  const newState: GameState = {
    ...state,
    player: {
      ...state.player,
      attackCooldown: spec.cooldownMs,
    },
    enemies: newEnemies,
    score: finalScore,
  }

  return { state: newState, events }
}
