import { chromium } from 'playwright'
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms))
const b=await chromium.launch()
const p=await (await b.newContext({viewport:{width:1280,height:720}})).newPage()
const errs=[]; p.on('pageerror',e=>errs.push(e.message))
await p.goto('http://localhost:5180/')
await p.waitForFunction(()=>{try{return !!(window.__game&&window.__game.registry&&window.__game.registry.get('adService'))}catch(e){return false}},null,{timeout:30000})
await p.evaluate(()=>{const o=document.getElementById('loader-overlay');if(o)o.style.display='none'})
const kind=await p.evaluate(()=>window.__game.registry.get('adService').constructor.name)
console.log('adService =', kind)
await p.evaluate(()=>{const ad=window.__game.registry.get('adService');ad.showRewarded().then(r=>{window.__adR=r})})
await sleep(1300)
await p.screenshot({path:'/tmp/loop-shots/adsim-rewarded-1.png'})
await sleep(5300)
await p.screenshot({path:'/tmp/loop-shots/adsim-rewarded-2.png'})
console.log(errs.length?'ERR: '+errs.join(' | '):'no page errors')
await b.close()
