import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest'
import { boot, ColyseusTestServer } from '@colyseus/testing'
import { matchMaker } from '@colyseus/core'
import appConfig from '../src/app.config'
import type { ArenaRoom } from '../src/rooms/ArenaRoom'

// ── Room-code contract tests ───────────────────────────────────────────────────
// These verify the custom roomId (4 uppercase letters A-Z) generated by
// ArenaRoom.onCreate via the Presence-based recipe (docs.colyseus.io/recipes/custom-room-id).
// The testing harness drives the server in-process, so colyseus.createRoom() returns
// the LIVE Room instance whose .roomId is the custom code.

describe('Room codes (custom roomId via Presence)', () => {
  let colyseus: ColyseusTestServer

  beforeAll(async () => { colyseus = await boot(appConfig) })
  afterAll(async () => { await colyseus.shutdown() })
  beforeEach(async () => { await colyseus.cleanup() })

  it('created room has a roomId matching /^[A-Z]{4}$/', async () => {
    const room = await colyseus.createRoom('arena', {})
    expect(room.roomId).toMatch(/^[A-Z]{4}$/)
  })

  it('two rooms get distinct codes', async () => {
    const r1 = await colyseus.createRoom('arena', {})
    const r2 = await colyseus.createRoom('arena', {})
    expect(r1.roomId).toMatch(/^[A-Z]{4}$/)
    expect(r2.roomId).toMatch(/^[A-Z]{4}$/)
    expect(r1.roomId).not.toBe(r2.roomId)
  })

  it('joinById(code) lands the client in the correct room', async () => {
    const room = await colyseus.createRoom('arena', {})
    const code = room.roomId

    // colyseus.sdk.joinById uses the matchMaker's joinById path, which
    // looks up by roomId — exercising the exact same path a real client would.
    const sdkRoom = await colyseus.sdk.joinById(code, { charKey: 'werdum' })
    expect(sdkRoom.roomId).toBe(code)
    sdkRoom.leave()
  })

  it('joinById with a nonexistent code rejects', async () => {
    // 'ZZZZ' is not registered — the matchMaker must throw.
    await expect(
      colyseus.sdk.joinById('ZZZZ', { charKey: 'werdum' }),
    ).rejects.toBeDefined()
  })
})

// ── Exposed matchmaking methods ────────────────────────────────────────────────
// matchMaker.controller.exposedMethods must contain ONLY the four safe methods.
// 'joinOrCreate' is removed so clients cannot do open matchmaking (they must use
// an explicit room code or create their own room as host).
// NOTE: 'create' stays exposed in this Fatia (beta web, no host gate yet).
//       The premium host gate (restrict create to server-side / paid users) is
//       planned for Fatia 4.

describe('matchMaker.controller.exposedMethods (restricted matchmaking)', () => {
  let colyseus: ColyseusTestServer

  beforeAll(async () => { colyseus = await boot(appConfig) })
  afterAll(async () => { await colyseus.shutdown() })

  it('exposed methods are exactly [create, joinById, reconnect] (no open matchmaking)', () => {
    const methods = [...matchMaker.controller.exposedMethods].sort()
    // joinOrCreate and join are intentionally removed: clients must use an
    // explicit room code (joinById) or act as host (create). Open matchmaking
    // would allow joining any room without a code.
    expect(methods).toEqual(['create', 'joinById', 'reconnect'])
  })

  it('invokeMethod joinOrCreate is rejected (not exposed)', async () => {
    await expect(
      matchMaker.controller.invokeMethod('joinOrCreate', 'arena', {}),
    ).rejects.toBeDefined()
  })

  it('invokeMethod join is rejected (not exposed — would bypass code gate)', async () => {
    await expect(
      matchMaker.controller.invokeMethod('join', 'arena', {}),
    ).rejects.toBeDefined()
  })
})
